export const agentsData = [
  {
    name: 'Leo',
    role: 'master',
    rank: 2,
    missions_succeed: 129,
    missions_failed: 8,
    isCalled: false,
  },
  {
    name: 'Mark',
    role: 'agent',
    rank: 16,
    missions_succeed: 55,
    missions_failed: 4,
    isCalled: true,
  },
  {
    name: 'Ophelia',
    role: 'agent',
    rank: 19,
    missions_succeed: 48,
    missions_failed: 5,
    isCalled: true,
  },
  {
    name: 'Varys',
    role: 'agent',
    rank: 14,
    missions_succeed: 69,
    missions_failed: 4,
    isCalled: false,
  },
  {
    name: 'Lorana',
    role: 'master',
    rank: 4,
    missions_succeed: 111,
    missions_failed: 6,
    isCalled: false,
  },
  {
    name: 'Zen',
    role: 'agent',
    rank: 22,
    missions_succeed: 20,
    missions_failed: 2,
    isCalled: true,
  },
  {
    name: 'Peter',
    role: 'agent',
    rank: 24,
    missions_succeed: 18,
    missions_failed: 3,
    isCalled: false,
  },
];

